name: Kopier fil til gh-pages

on:
  workflow_run:
    workflows: ["01 Build and Deploy Site"]
    types:
      - completed

jobs:
  kopier-fil:
    # 2024-10-01: ubuntu latest is now 24.04 and R is not installed by default in the runner image
    # pin to 22.04 for now
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Download fil fra internettet
        run: curl -o logotest.svg https://kubdatalab.github.io/R-intro/fig/logotest.svg

      - name: Kopier fil til det bestemte sted
        run: mv logotest.svg assets/images/library-logo.svg

      - name: Commit og push ændringer
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Opdateret fil på gh-pages"
          git push
